In [5]:
# tensorflow 初見 (使用 tf v1)
import tensorflow.compat.v1 as tf
import numpy as np
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [15]:
# 常數 tensor
ts_c = tf.constant(2, name='ts_c')
ts_c

<tf.Tensor 'ts_c_1:0' shape=() dtype=int32>

In [16]:
# 變數 tensor
ts_x = tf.Variable(ts_c+5, name='ts_x')
ts_x

<tf.Variable 'ts_x_1:0' shape=() dtype=int32_ref>

In [17]:
# 建立 Session 並初始化
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [18]:
# 運行 Session
print('ts_c=', sess.run(ts_c))
print('ts_x=', sess.run(ts_x))

ts_c= 2
ts_x= 7


In [19]:
# 使用 eval 方式 運行 Session
print('ts_c=', ts_c.eval(session=sess))
print('ts_x=', ts_x.eval(session=sess))

ts_c= 2
ts_x= 7


In [20]:
# 關閉 session
sess.close()

In [21]:
# 使用 with ，可以在執行 session 執行後自動關閉
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c=', sess.run(ts_c))
    print('ts_x=', sess.run(ts_x))

ts_c= 2
ts_x= 7


In [22]:
# tensorflow 可以先建立算圖才放入數值 (像 function 一樣)
width = tf.placeholder("int32")
height = tf.placeholder("int32")
area = tf.multiply(width, height)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width:6, height:5}))

area= 30


In [23]:
# tensorflow 其他常見運算符
x = tf.placeholder("int32")
y = tf.placeholder("int32")
d = tf.placeholder("float32")
area = tf.multiply(width, height)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('加', sess.run(tf.add(        x, y), feed_dict={x:1, y:2}))
    print('減', sess.run(tf.subtract(   x, y), feed_dict={x:1, y:2}))
    print('乘', sess.run(tf.multiply(   x, y), feed_dict={x:1, y:2}))
    print('除', sess.run(tf.divide(     x, y), feed_dict={x:1, y:2}))
    print('取餘', sess.run(tf.mod(      x, y), feed_dict={x:5, y:3}))
    print('平方', sess.run(tf.sqrt(     d), feed_dict={d:2}))
    print('絕對值', sess.run(tf.abs(   x), feed_dict={x:1.5}))

加 3
減 -1
乘 2
除 0.5
取餘 2
平方 1.4142135
絕對值 1


In [24]:
# tensorboard 算圖
width = tf.placeholder("int32")
height = tf.placeholder("int32")
area = tf.multiply(width, height)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width:6, height:5}))
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('tensorboard/area', sess.graph)

area= 30


In [25]:
# 建立 1 唯 list 
ts_X = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)
    print('shape:', X.shape)

[0.4 0.2 0.4]
shape: (3,)


In [26]:
# 建立 2 唯 list 
ts_W = tf.Variable([
        [-0.5, -0.2],
        [-0.3, 0.4],
        [-0.5, 0.2]
])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W=sess.run(ts_W)
    print(W)
    print('shape:', W.shape)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]
shape: (3, 2)


In [27]:
# tensorflow 矩陣運算
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([
        [-0.5, -0.2],
        [-0.3, 0.4],
        [-0.5, 0.2]
])
XW = tf.matmul(X, W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(1, 3), b.shape=(3, 2), m=1, n=2, k=3
	 [[node MatMul (defined at <ipython-input-27-f373216ffdef>:8) ]]
	 [[MatMul/_7]]
  (1) Internal: Blas GEMM launch failed : a.shape=(1, 3), b.shape=(3, 2), m=1, n=2, k=3
	 [[node MatMul (defined at <ipython-input-27-f373216ffdef>:8) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MatMul:
 Variable_4/read (defined at <ipython-input-27-f373216ffdef>:2)	
 Variable_5/read (defined at <ipython-input-27-f373216ffdef>:6)

Input Source operations connected to node MatMul:
 Variable_4/read (defined at <ipython-input-27-f373216ffdef>:2)	
 Variable_5/read (defined at <ipython-input-27-f373216ffdef>:6)

Original stack trace for 'MatMul':
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 759, in _run_callback
    ret = callback()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-f373216ffdef>", line 8, in <module>
    XW = tf.matmul(X, W)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 3254, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5642, in mat_mul
    name=name)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()


In [3]:
# tensorflow 矩陣加法
b  = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3, 0.4]])

Sum = XW + b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum: ')
    print(sess.run(Sum))

Sum: 
[[-1.1999999  0.6      ]]


In [4]:
# tensorflow 矩陣乘法 加法
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([
        [-0.5, -0.2],
        [-0.3, 0.4],
        [-0.5, 0.2]
])
b  = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X, W) + b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XWb))

InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(1, 3), b.shape=(3, 2), m=1, n=2, k=3
	 [[node MatMul (defined at <ipython-input-4-a81f29d90f0e>:10) ]]
	 [[add_1/_1]]
  (1) Internal: Blas GEMM launch failed : a.shape=(1, 3), b.shape=(3, 2), m=1, n=2, k=3
	 [[node MatMul (defined at <ipython-input-4-a81f29d90f0e>:10) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MatMul:
 Variable_3/read (defined at <ipython-input-4-a81f29d90f0e>:6)	
 Variable_2/read (defined at <ipython-input-4-a81f29d90f0e>:2)

Input Source operations connected to node MatMul:
 Variable_3/read (defined at <ipython-input-4-a81f29d90f0e>:6)	
 Variable_2/read (defined at <ipython-input-4-a81f29d90f0e>:2)

Original stack trace for 'MatMul':
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 759, in _run_callback
    ret = callback()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-a81f29d90f0e>", line 10, in <module>
    XWb = tf.matmul(X, W) + b
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 3254, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5642, in mat_mul
    name=name)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()


In [2]:
# tensorflow 亂數生成
b = tf.Variable(tf.random_normal([1, 2]))
W = tf.Variable(tf.random_normal([3, 2]))
X = tf.Variable([[ 0.4, 0.2, 0.4]])
y = tf.matmul(X,W)+ b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('b: ');print(sess.run(b ))
    print('W: ');print(sess.run(W ))
    print('y: ');print(sess.run(y ))

b: 
[[0.2157984  0.12679936]]
W: 
[[ 1.4790143   0.06213768]
 [ 0.6590696  -0.20579012]
 [ 0.38795695  0.52980375]]
y: 


InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(1, 3), b.shape=(3, 2), m=1, n=2, k=3
	 [[node MatMul (defined at <ipython-input-2-9b96e617ff14>:5) ]]
  (1) Internal: Blas GEMM launch failed : a.shape=(1, 3), b.shape=(3, 2), m=1, n=2, k=3
	 [[node MatMul (defined at <ipython-input-2-9b96e617ff14>:5) ]]
	 [[add/_5]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MatMul:
 Variable_1/read (defined at <ipython-input-2-9b96e617ff14>:3)	
 Variable_2/read (defined at <ipython-input-2-9b96e617ff14>:4)

Input Source operations connected to node MatMul:
 Variable_1/read (defined at <ipython-input-2-9b96e617ff14>:3)	
 Variable_2/read (defined at <ipython-input-2-9b96e617ff14>:4)

Original stack trace for 'MatMul':
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-9b96e617ff14>", line 5, in <module>
    y = tf.matmul(X,W)+ b
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 3254, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5642, in mat_mul
    name=name)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "D:\Users\tom83615\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()


In [ ]:
# tensorflow 縮減執行(只需 run 一次)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b,_W,_y) = sess.run((b,W,y))
    print('b: ');print(_b)
    print('W: ');print(_W)
    print('y: ');print(_y)

In [1]:
# tensorflow 導入激活函數(線性)
y = tf.nn.relu(tf.matmul(X,W)+ b)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_b,_W,_y) = sess.run((b,W,y))
    print('b: ');print(_b)
    print('W: ');print(_W)
    print('y: ');print(_y)

NameError: name 'tf' is not defined

In [2]:
# tensorflow 製作亂數測資
ts_norm = tf.random_normal([1000])
with tf.Session() as session:
    norm_data = ts_norm.eval()
print(norm_data[:5])

import matplotlib.pyplot as plt
plt.hist(norm_data)
plt.show()

NameError: name 'tf' is not defined

In [3]:
# tensorflow 導入 placeholder
b = tf.Variable(tf.random_normal([1, 2]))
W = tf.Variable(tf.random_normal([3, 2]))
X = tf.placeholder("float", [None, 3])
y = tf.nn.relu(tf.matmul(X,W)+ b)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([
        [0.4, 0.2, 0.4],
        [0.3, 0.4, -0.6]
    ])
    (_b,_W,_X,_y) = sess.run((b,W,X,y), feed_dict={X:X_array})
    print('b: ');print(_b)
    print('W: ');print(_W)
    print('X: ');print(_X)
    print('y: ');print(_y)

NameError: name 'tf' is not defined

In [6]:
# 建立一個類神經網路 demo 
# 輸入層 4 個神經元 X
# 隱藏層 3 個神經元 h
# 輸出層 2 個神經元 y
import otherLib as olib
olib.solve_cudnn_error() # 處理 GPU memory 分配
X = tf.placeholder("float", [None, 4])
h = olib.tf_layer(3, 4, X, activation=tf.nn.relu)
y = olib.tf_layer(2, 3, h)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    (layer_X, layer_h, layer_y) = sess.run((X,h,y), feed_dict={X:X_array})
    print('input layer X: ');print(layer_X)
    print('hidden Layer h: ');print(layer_h)
    print('output Layer y: ');print(layer_y)

1 Physical GPUs, 1 Logical GPUs
input layer X: 
[[0.4 0.2 0.4 0.5]]
hidden Layer h: 
[[1.9387515 1.0352714 0.6354359]]
output Layer y: 
[[ 1.676548  -3.4299762]]


In [9]:
# 查看 weight 與 bias
X = tf.placeholder("float", [None, 4])
h, Wh, bh = olib.tf_layer_debug(3, 4, X, activation=tf.nn.relu)
y, Wy, by = olib.tf_layer_debug(2, 3, h)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
    (layer_X, layer_h, layer_y, Wh, Wy, bh, by)= sess.run((X,h,y, Wh, Wy, bh, by), feed_dict={X:X_array})
    print('input layer X: ');print(layer_X)
    
    print('hidden Layer weight: ');print(Wh)
    print('hidden Layer bias: ');print(bh)
    print('hidden Layer h: ');print(layer_h)

    print('output Layer weight: ');print(Wy)
    print('output Layer bias: ');print(by)
    print('output Layer y: ');print(layer_y)

input layer X: 
[[0.4 0.2 0.4 0.5]]
hidden Layer h: 
[[0. 0. 0.]]
output Layer y: 
[[-2.4479735   0.38027957]]
hidden Layer weight: 
[[ 0.44766223 -0.46026507  0.20368063]
 [ 0.8051307   0.8468793  -0.27112734]
 [ 1.6560757  -0.8413228  -0.05774757]
 [-0.91051525  0.8247382   0.06021276]]
hidden Layer bias: 
[[-0.7229003  -0.76628333 -0.08796461]]
output Layer weight: 
[[-0.3874225   0.80883276]
 [ 0.09661663  0.17161855]
 [ 0.2666934  -0.55275774]]
output Layer bias: 
[[-2.4479735   0.38027957]]
